### ISSUE TITLE
docs: add commented out `maximize_build_space: true` to build.yml

### ISSUE THREAD

**Issue by johnr14** [blue-build/template#33]
Hi, I have ran into a problem where the instance didn't have enought space during build time when working with a big image like Bazzite.

I added this to my `.github/workflows/build.yml`
```
      # If you ran out of space during build, this should help
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7
```

as first `steps:` of `bluebuild:`

It takes about a minute and results in `Total reclaimed space: 3.141GB`

Could be added to default template as a comment.

Thanks

**Comment by fiftydinar** [comment]
We already documented the use of "Maximize build space" action as an option in build.yml.

https://blue-build.org/reference/github-action/#maximize_build_space-optional

Try this one, as it's different from ublue-os "Maximize build space" action.

We use this one:

https://github.com/jlumbroso/free-disk-space

**Comment by johnr14** [comment]
I was looking at the code and [found](https://github.com/blue-build/github-action/blob/8f4a6129fa195e9a35648b24e1a6b32269e04854/action.yml#L88-L90) the solution

```  - name: Maximize build space
      uses: jlumbroso/free-disk-space@v1.3.1
      if: ${{ inputs.maximize_build_space == 'true' }}
```
Just a bit before I saw your reply.

It did build with my image with the ublue-os action.
Did the rebuild with free-disk-space and it resulted in : `  Saved 4.7GiB`

Sorry my fault for not seeing it in the documentation.

I'd would have preferred the template to include all sane options with their default and commented out. It would make it more self explanatory.

Just pasting in case someone else search issues instead or reading the docs :) 

```
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6.0
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          #use_unstable_cli: false # this action pulls the main branch of blue-build/cli instead of the stable version
          maximize_build_space: true # run the unwanted software remover to maximize build space 
          squash: true
```

Thanks for your great work !
